sockets_extension.go, sockets_extension_test.go
Those methods are useful to get proper formatting of `wasi.SocketAddress` struct fields when marshaling to JSON or YAML.
=> implement interfaces to marshal socket addresses to json/yaml

imports/wasi_snapshot_preview1/module.go, imports/wasi_snapshot_preview1/wasmedge.go, sockets_extension.go, system.go, systems/unix/system.go, tracer.go
This change makes it possible to know the pair of local and remote addresses when accepting connections from a pre-open file descriptor, in cases where SockLocalAddress was never called by the guest application. It also results in having all the information needed to construct a `net.Conn` without having to make an extra call.
I also added a second commit to rename `SockPeerAddress` to `SockRemoteAddress`, the correspondence between Local/Remote is more coherent than Local/Peer, which I think we had derived from the WasmEdge ABI. It also reuses the naming of Go's `net` package, making API more familiar to developers.
=> export socket pairs when accepting/connecting

systems/unix/system.go, tracer.go
In https://github.com/stealthrocket/wasi-go/pull/37, `SockConnect` was updated to return the local address that the connection was made from.
This PR fixes the unix implementation to do that, and to correctly handle `EINPROGRESS` errors.
=> unix: fix SockConnect return addr

imports/builder_unix.go, imports/wasi_snapshot_preview1/module.go, system.go, systems/unix/file.go, systems/unix/path_open_sockets.go, systems/unix/readdir_darwin.go, systems/unix/readdir_linux.go, systems/unix/syscall_linux.go, systems/unix/system.go, systems/unix/system_test.go, tracer.go, wasi.go
I would like to suggest a refactor to extract the file tables and most of the generic logic out of `unix.System` and into a `wasi.FileTable[File]` type.
The decoupling of the file table operations, and actual invocation of operations on a file makes it possible to experiment with new implementations of `wasi.System` which are not wrappers but bottom layers (like `unix.System` but potentially having a different implementation). With this model, we can implement only the specialized parts. It accelerates our ability to create new systems and ensures that we minimize the risks of seeing divergence of behaviors.
Please take a look and let me know if you would like to see anything changed!
=> wasi: generic file table

go.mod, go.sum, imports/wasi_snapshot_preview1/wasmedge.go
I incorrectly assumed that WasmEdge's v1 `sock_getlocaladdr` and `sock_getpeeraddr` functions would expect either `AF_INET` or `AF_INET6` for the address type. Instead, they expect either 4 or 6 ([reference](https://github.com/second-state/wasmedge_wasi_socket/blob/7e49c11063b0bee93f48a294122565dd2c9c8349/src/socket.rs#L851-L854)).
With this fix, we're able to run the WasmEdge HTTP server examples, e.g. https://github.com/WasmEdge/wasmedge_hyper_demo.
=> wasmedge: fix v1 getlocaladdr/getpeeraddr

error.go, imports/builder.go, imports/builder_unix.go, internal/sockets/dial.go, internal/sockets/listen.go, internal/sockets/socket.go, systems/unix/syscall_darwin.go, tracer.go, wasi.go
This PR addresses a bug that was causing the host fd 0 to be closed unexpectedly when any guest file descriptors were closed.
The bug was introduced by the refactor in #38
=> wasi: fix closing of file descriptors

go.mod, go.sum, imports/wasi_snapshot_preview1/module.go, imports/wasi_snapshot_preview1/wasmedge.go, sockets_extension.go, systems/unix/system.go, systems/unix/system_test.go, tracer.go
This PR implements the `sock_getaddrinfo` host function from WasmEdge.
I chose not to use `getaddrinfo(3)` directly, to avoid CGO, but also because I'd need different implementations for Linux and macOS. Rather, I'm using `net.LookupIP` and `net.LookupPort` to implement a subset of the functionality offered by `getaddrinfo(3)`.
Reference:
* https://github.com/WasmEdge/WasmEdge/blob/d2fc0ffc/thirdparty/wasi/api.hpp
* https://github.com/WasmEdge/WasmEdge/blob/d2fc0ffc/lib/host/wasi/wasifunc.cpp#L2132
* https://github.com/WasmEdge/WasmEdge/blob/d2fc0ffc/lib/host/wasi/inode-linux.cpp#L796
* https://github.com/second-state/wasmedge_wasi_socket/blob/7e49c110/src/socket.rs#L138
* https://github.com/second-state/wasmedge_wasi_socket/blob/7e49c110/src/lib.rs#L322
_Cargo.toml_
```toml
[package] …
```
=> wasmedge: support sock_getaddrinfo

imports/wasi_snapshot_preview1/wasmedge.go, sockets_extension.go, systems/unix/system.go, tracer.go
This PR generalizes the `setsockopt` / `getsockopt` wrappers we had. Previously we had `Sock{Get,Set}OptInt` system calls.
There are a few WasmEdge socket options we don't support yet because the option values have different types (e.g. `struct linger`, `struct timeval`, `char [IFNAMSZ]`), and there are many more weird and wonderful socket options out there:
Let's try to stick close to the operating system here. `setsockopt` and `getsockopt` accept and populate a `(void *option_value, socklen_t option_len)` respectively. We can use the same approach as our `SocketAddress` and make a polymorphic `SocketOptionValue` type. As new socket options and values are required in future, we can provide additional implementations of `SocketOptionValue` and can avoid adding new methods to the …
=> wasi: polymorphic socket option values

fs.go, systems/unix/file.go, systems/unix/system_test.go, wasi.go
The Go stdlib has a great test suite in `testing/fstest` to validate the implementation of file-system-like types. I added a `wasi.FS` function which wraps a `wasi.System` and creates an adapter between the two interfaces so we can use the test suite to verify the behavior of WASI systems.
The tests highlighted one issue with the selection of open flags in path_open, which is fixed here as well.
=> wasi: add wasi.System adapter to fs.FS

systems/unix/file.go, systems/unix/readdir_darwin.go, systems/unix/readdir_linux.go, systems/unix/syscall_unix.go, systems/unix/system.go
Based on #58, I noticed that sometimes the tests would fail due to signals interrupting syscalls when repeating tests with `-count`, likely caused by Go's preemptive goroutine scheduling which is based on delivering signals to threads.
The Go stdlib handles EINTR, preventing applications from seeing the error, I believe we should do this as well in the `unix.System` implementation (I left a comment in the code explaining the reasoning for WASI).
=> systems/unix: handle EINTR

systems/unix/system.go
This PR ensures unix socket addresses are consistent across platforms. Only Linux, empty unix socket addresses are seen as `@` because the Go standard library and /x/sys package consider them to be abstract sockets (when the first byte in the address is a null byte). On other platforms, the unix socket address is instead an empty string.
=> unix: consistent unix socket addresses

imports/wasi_snapshot_preview1/wasmedge.go, socket.go, systems/unix/system.go
The Python Requests library set TCP_NODELAY on sockets by default.
=> Add TCP_NODELAY socket option

wasitest/poll.go
Quick fix for issues that triggered while using `wasitest`.
=> wasitest: fix sync in poll test

systems/unix/system.go, wasitest/socket.go
This PR adds more socket tests for better coverage of socket lifecycles and validates greater portability across platforms.
=> wasitest: more socket tests

systems/unix/system.go, wasitest/socket.go
This PR adds a test to verify bidirectional socket communication on TCP streams.
=> wasitest: test bidirectional socket communication

socket.go, systems/unix/system.go, wasitest/socket.go
This PR adds more tests to verify the behavior of sockets in blocking mode; they are copies of tests used in non-blocking mode with the `poll_oneoff` calls removed.
I aloso implemented `SO_RCVTIMEO` and `SO_SNDTIMEO` since those options apply to blocking mode.
=> wasitest: add tests for sockets in blocking mode

systems/unix/system.go
Follow up to https://github.com/stealthrocket/wasi-go/pull/68, the address family was never set.
=> addrinfo: set family

cmd/wasirun/main.go, go.mod, imports/wasi_snapshot_preview1/wasmedge.go, systems/unix/system.go
This PR modifies `wasirun` to use `net.DefaultResolver` so we can configure the DNS servers for `SockAddressInfo` and propagate the context for asynchronous cancellation.
=> addrinfo: use default resolver

imports/builder_unix.go
This change allows `wasi-go` tests to run on gitpod, see https://github.com/gitpod-io/gitpod/issues/17551
=> Handle stdio permission error

wasi.go
This PR adds a method to `wasi.FileTable` to support declaring an open file descriptor as a preopen. This is useful when performing initialization of the `wasi.System` prior to instantiating a module, and the host needs to configure the file descriptors it created as preopens.
=> wasi: add FileTable.PreopenFD method

imports/wasi_snapshot_preview1/wasmedge.go, socket.go, system.go, systems/unix/system.go, tracer.go, wasitest/socket.go
This patch makes two main changes:
- Allow options of variable lengths to be passed through `SockSetOpt`.
- Modify `SockSetOpt` and `SockGetOpt` to merge option and level into one value.
The main goal is to enable extensions of socket options by the implementations of `wasi.System`, without having to teach wasi-go about them.
=> socket: long options

systems/unix/system.go, wasitest/socket.go
This PR adds a test to verify that `sendto` cannot be used on connected datagram sockets.
=> wasitest: test sendto on connected datagram sockets

systems/unix/system.go, wasitest/poll.go, wasitest/socket.go
Those tests verify edge cases when sockets are polled on before they are connected:
- for stream sockets, no events should trigger
- for datagram sockets, writing is supported as soon as the socket is created so the write event must trigger
=> wasitest: add tests to validate the polling of sockets before they are connected

cmd/wasirun/main.go
This enables `GOOS=wasip1 GOARCH=wasm go test -exec 'wasirun --env-inherit --dir /' <package>`
The `go test` command sets the working directory AND `$PWD` to the package source directory when running. This passes `PWD` through at the time `wasirun` is executed, rather than the value of `PWD` at the time `go test` is executed (typically the module root).
=> cmd/wasirun: add --env-inherit flag from wazero

imports/wasi_http/README.md
Fixed mistyped dev-wasm-dotnet URL in imports/wasi_http/README.md .
=> Fixed mistyped dev-wasm-dotnet URL in wasi_http

cmd/wasirun/main.go, imports/builder.go, imports/builder_unix.go, systems/unix/file.go, systems/unix/system.go, systems/unix/system_test.go, wasi.go, wasitest/file.go, wasitest/system.go, wasitest/wasip1.go
This PR adds two settings on the `wasi.FileTable` data structure to limit the number of open files and directories.
=> limit open files and directories

wasitest/file.go
Follow up to #84, this PR reduces the rights requested in `path_open` during the tests so they can pass on systems that apply more restrictions than `systems/unix.System`.
=> wasitest: ask for less rights in ENFILE tests

cmd/wasirun/main.go, imports/wasi_http/http.go, imports/wasi_http/http_test.go, imports/wasi_http/server/server.go
This fixes a bug where calls to wasi functions (e.g. `printf`) would crash.
=> Pass context to fix calls to wasip1

systems/unix/system.go, systems/unix/system_test.go
From `getaddrinfo(3)`:
> If the AI_PASSIVE flag is specified in hints.ai_flags, and node is NULL, then the returned socket addresses will be suitable for bind(2)ing a socket that will accept(2) connections. The returned socket address will contain the "wildcard address" (INADDR_ANY for IPv4 addresses, IN6ADDR_ANY_INIT for IPv6 address).  The wildcard address is used by applications (typically servers) that intend to accept connections on any of the host's network addresses. If node is not NULL, then the AI_PASSIVE flag is ignored.
> If the AI_PASSIVE flag is not set in hints.ai_flags, then the returned socket addresses will be suitable for use with connect(2), sendto(2), or sendmsg(2). If node is NULL, then the network address will be set to the loopback interface address (INADDR_LOOPBACK …
=> wasi: support empty getaddrinfo name without AI_PASSIVE

imports/builder_default.go
Some existing codebase under Unix was using builder.Instanciate() that returns 3 values.
My IDE was complaining because it was expecting only 2 values returned.
It turns out: I should simply not try to compile it under Windows.
Signatures both for the `default` and the `_unix` should be the same to avoid such error.
=> Same signature both for Unix and Windows
